# 字幕スタイル
styles:
  reimu:
    font_name: "Yu Gothic"
    font_size: 48
    primary_color: "&H00FFFFFF"
    outline_color: "&H00000000"
    position: "bottom"

  marisa:
    font_name: "Yu Gothic"
    font_size: 48
    primary_color: "&H0000FFFF"
    outline_color: "&H00000000"
    position: "bottom"
